### ISSUE TITLE
Remove code duplication on server.go

### ISSUE THREAD

**Issue by gmelodie** [MLH-Fellowship/FellowshipWrapup#34]
There's a lot of duplicated code on [`server.go`](https://github.com/MLH-Fellowship/FellowshipWrapup/blob/master/backend/server/server.go), we should remove that and make a function that receives a query and just does it. Also, if such a function is implemented, it would make sense to move it to the `queries` package.

**Comment by IamCathal** [comment]
Some of the logic such as the line below would either require a switch statement (3 times per function at the moment) or some clever trick that I don't know of. Manly because you can can't have a variable struct name really without a string variable for it and then using a switch statement to deduce the actual struct type in it's own case

https://github.com/MLH-Fellowship/FellowshipWrapup/blob/7d2f7c4daa41956c86b7c81b822c33d651c53cf2/backend/server/server.go#L91

**Comment by IamCathal** [comment]
Fixed in https://github.com/MLH-Fellowship/FellowshipWrapup/pull/38
